env:
  CODECOV_TOKEN: a2d17ea7-57f0-4612-9f2e-3ac77cf30c32
  JULIA_NUM_THREADS: auto
  PYTHON: ""
  PYCALL_DEBUG_BUILD: yes

steps:
  - label: "QuantumOptics Tests - {{matrix.LABEL}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      JET_TEST: "{{matrix.JET_TEST}}"
      CUDA_TEST: "{{matrix.CUDA_TEST}}"
      AMDGPU_TEST: "{{matrix.AMDGPU_TEST}}"
      OpenCL_TEST: "{{matrix.OPENCL_TEST}}"
    agents:
      queue: "{{matrix.QUEUE}}"
    matrix:
      setup:
        LABEL: ["base tests"]
        QUEUE: ["default"]
        JET_TEST: ["false"]
        CUDA_TEST: ["false"]
        AMDGPU_TEST: ["false"]
        OPENCL_TEST: ["false"]
      adjustments:
        - with:
            LABEL: "JET"
            QUEUE: default
            JET_TEST: true
            CUDA_TEST: false
            AMDGPU_TEST: false
            OPENCL_TEST: false
        - with:
            LABEL: "CUDA"
            QUEUE: cuda
            JET_TEST: false
            CUDA_TEST: true
            AMDGPU_TEST: false
            OPENCL_TEST: false
        - with:
            LABEL: "OpenCL"
            QUEUE: default
            JET_TEST: false
            CUDA_TEST: false
            AMDGPU_TEST: false
            OPENCL_TEST: true