env:
  CODECOV_TOKEN: a2d17ea7-57f0-4612-9f2e-3ac77cf30c32
  JULIA_NUM_THREADS: auto
  PYTHON: ""
  PYCALL_DEBUG_BUILD: yes

steps:
  - label: "Package Tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true

  - label: "JET Tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      JET_TEST: true

  - label: "CUDA Tests"
    agents:
      queue: cuda
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      CUDA_TEST: true

#  - label: "AMDGPU Tests"
#    agents:
#      queue: rocm
#    plugins:
#      - JuliaCI/julia#v1:
#          version: "1"
#      - JuliaCI/julia-test#v1:
#      - JuliaCI/julia-coverage#v1:
#          codecov: true
#    env:
#      AMDGPU_TEST: true

  - label: "OpenCL Tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      OpenCL_TEST: true