env:
  JULIA_NUM_THREADS: auto
  PATH: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH}

secrets:
  CODECOV_TOKEN: CODECOV_TOKEN_qojulia

steps:
  - label: "QuantumOptics Tests - {{matrix.LABEL}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      JET_TEST: "{{matrix.JET_TEST}}"
      GPU_TEST: "{{matrix.GPU_TEST}}"
    agents:
      queue: "{{matrix.QUEUE}}"
    matrix:
      setup:
        LABEL: ["base tests"]
        QUEUE: ["default-queue"]
        JET_TEST: ["false"]
        GPU_TEST: ["false"]
      adjustments:
        - with:
            LABEL: "JET"
            QUEUE: default-queue
            JET_TEST: true
            GPU_TEST: false
        - with:
            LABEL: "CUDA"
            QUEUE: cuda
            JET_TEST: false
            GPU_TEST: cuda
        - with:
            LABEL: "AMDGPU"
            QUEUE: rocm
            JET_TEST: false
            GPU_TEST: amdgpu
        - with:
            LABEL: "OpenCL"
            QUEUE: default-queue
            JET_TEST: false
            GPU_TEST: opencl
        - with:
            LABEL: "Metal"
            QUEUE: macmini
            JET_TEST: false
            GPU_TEST: metal

  - label: "Docs"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
    secrets:
      DOCUMENTER_KEY: DOCUMENTER_KEY_QuantumOptics
      ANYTHINGLLM_API_KEY: ANYTHINGLLM_API_KEY
    env:
      MPLBACKEND: Agg
    command: |
      PYTHON_BIN="$$(command -v python3 || command -v python)"
      "$$PYTHON_BIN" -m pip install --user jupyter nbconvert nbformat matplotlib==3.8.3
      USER_BIN="$$($$PYTHON_BIN -m site --user-base)/bin"
      export PATH="$${USER_BIN}:$${PATH}"
      export PYTHON="$$PYTHON_BIN"
      echo "Setting PYTHON=$PYTHON"
      export PYCALL_DEBUG_BUILD="yes"
      julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
      julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.build("PyCall")'
      julia -tauto --project=docs docs/make.jl

  - label: "Downstream Tests - {{matrix.PACKAGE}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project=$(mktemp -d) -e '
        using Pkg;
        pkg"dev .";
        Pkg.add("{{matrix.PACKAGE}}");
        Pkg.build("{{matrix.PACKAGE}}");
        Pkg.test("{{matrix.PACKAGE}}");'
    matrix:
      setup:
        PACKAGE: ["QuantumSavory", "WaveguideQED"]
