# Post benchmark results as PR comments in a privileged environment.
# This workflow is triggered by the completion of the "Benchmarks" workflow
# and uses artifacts to securely pass data between unprivileged and privileged contexts.
# See: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: Benchmark Comment

on:
  workflow_run:
    workflows:
      - Benchmarks
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
          github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6

      - uses: dawidd6/action-download-artifact@v14
        with:
          workflow: benchmark.yml
          name: benchmark-result
          workflow_conclusion: success

      - name: Read benchmark result
        id: output-result-markdown
        run: |
          echo ::set-output name=body::$(cat ./benchmark-result.artifact)

      - name: Read pull request number
        id: output-pull-request-number
        run: |
          echo ::set-output name=body::$(cat ./pull-request-number.artifact)

      - name: Find existing comment
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ steps.output-pull-request-number.outputs.body }}
          comment-author: 'github-actions[bot]'
          body-includes: Benchmark Result

      - name: Create comment
        if: ${{ steps.fc.outputs.comment-id == 0 }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ steps.output-pull-request-number.outputs.body }}
          body: ${{ steps.output-result-markdown.outputs.body }}

      - name: Update comment
        if: ${{ steps.fc.outputs.comment-id != 0 }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.output-result-markdown.outputs.body }}
